### ISSUE TITLE
Implement logic to display user names in place of UUIDs in Issue Details

### ISSUE THREAD

**Issue by UnicornSnuggler** [PorkchopDonut/bug-tracker#25]
Right now the Issue Details form only populates the UUIDs attached to the issue in regards to the reporter and assignee values.  These need to be replaced with user names.  Devise a function (in the TerminalX.java) class to fetch the user name by their UUID and use that to populate the form's reporter and assignee values instead.

**Comment by ksherbondy** [comment]
I have been working on Issue-25 and Issue-16. While helping Joe push his commits I miss read the Issue number so his commit for Issue-16 is actually for Issue-15. Also, still figuring out GitHub so pretty much all of the issues I am working on will be pushed through this issue ticket. Don't know what is going on with my update function. It should be changing the issue.json file after the user hits update but, nothing changes. Also, depending on which issue is opened from the MainMenu screen the program will work or it will throw and error. Looks like if something is "null" in the json file after a user submits a new ticket (i.e. dev_Notes) is when the error is thrown.
