### ISSUE TITLE
Implement sorting logic for main menu

### ISSUE THREAD

**Issue by UnicornSnuggler** [PorkchopDonut/bug-tracker#32]
Write an ActionListener for the issues selection box that will sort the displayed issues when the sort by value is changed.

**Comment by ksherbondy** [comment]
How are we filtering the issues? 
By name- Only showing issues assigned to that individual?
By status - Order by priority from high to low/ new submission vs in development?
ID- show all?
Just trying to understand what you were thinking for this.

**Comment by UnicornSnuggler** [comment]
The list of issues that is present on the main menu is dictated by the `getIssues()` function within the main class.  All this ticket is referring to is the physical order in which they're sorted on the main menu screen.  Currently, they aren't being sorted; just being listed in the order that they're present in the database.  By default, we want to sort them by their titles.  Then the two other options will be present for alternative sorting methodologies.  None of these sorting methods will change which issues are present, simply their order in the list.

- **Name** - Sort the issues by their titles. [Default]
- **Status** - Sort the issues by their status (not priority) in ascending order of enum values (Backlog first, Archived last).
- **ID** - Sort the issues by their shortened UUID (in alphanumeric order).
