### ISSUE TITLE
Writing a function to transition enum values into humanized Strings

### ISSUE THREAD

**Issue by UnicornSnuggler** [PorkchopDonut/bug-tracker#9]
Currently, if you fetch an enum value and treat it as a string, it will be presented with underscores if it possesses them (such as `In_Development`).  Write up a function that will replace those underscores with spaces (as in `In Development`).

**Comment by ksherbondy** [comment]
Logan, 
As far as I can tell I have added the Enum to String functionality to all needed files. Committed and pushed my edits.
